# Generated by Django 5.0.6 on 2024-05-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('production_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('shift', models.CharField(max_length=50)),
            ],
        ),
    ]
